version: '3.8'
services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravel
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  webserver:
    image: httpd:latest
    container_name: apache_webserver
    restart: unless-stopped
    depends_on:
      - laravel-app
    volumes:
      - ./public:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
